<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PDN.TPS.Framework.Core.Bus" Version="9.0.10.58" />
    <PackageReference Include="PDN.TPS.Framework.Validator" Version="9.0.10.58" />
    <PackageReference Include="PDN.TPS.Framework.ViewModels" Version="9.0.10.58" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KSN.TPS.InvoiceHub.Common\KSN.TPS.InvoiceHub.Common.csproj" />
  </ItemGroup>

</Project>
