<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
	  <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
	 <RootNamespace>KSN.TPS.InvoiceHub.Api</RootNamespace>
  <AssemblyName>KSN.TPS.InvoiceHub.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\InvoiceInboxController.cs" />
    <Compile Remove="Controllers\WeatherForecastController.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="PDN.TPS.Framework.Ioc" Version="9.0.10.58" />
    <PackageReference Include="PDN.TPS.Framework.Web" Version="9.0.10.58" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KSN.TPS.InvoiceHub.ApplicationService.Contract\KSN.TPS.InvoiceHub.ApplicationService.Contract.csproj" />
    <ProjectReference Include="..\KSN.TPS.InvoiceHub.Common\KSN.TPS.InvoiceHub.Common.csproj" />
    <ProjectReference Include="..\KSN.TPS.InvoiceHub.Persistence\KSN.TPS.InvoiceHub.Persistence.csproj" />
    <ProjectReference Include="..\KSN.TPS.InvoiceHub.Query.DataContext\KSN.TPS.InvoiceHub.Query.DataContext.csproj" />
    <ProjectReference Include="..\KSN.TPS.InvoiceHub.QueryService.Contracts\KSN.TPS.InvoiceHub.QueryService.Contracts.csproj" />
  </ItemGroup>

</Project>
